In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC, SVR

from sklearn.metrics import confusion_matrix

import warnings
warnings.filterwarnings("ignore")

### Car Evaluation

In [4]:
car_columns = [
    "buying",
    "maint",
    "doors",
    "persons",
    "lug_boot",
    "safety",
    "class"
]

car_df = pd.read_csv(
    "dataset/car.data",
    header=None,
    names=car_columns
)

print("Car Evaluation Dataset")
print("Shape:", car_df.shape)

display(car_df.head())

Car Evaluation Dataset
Shape: (1728, 7)

  buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc

### Brain Cancer

In [5]:
brain_df = pd.read_csv(
    "dataset/DT-BrainCancer.csv"
)

print("Brain Cancer Dataset")
print("Shape:", brain_df.shape)

display(brain_df.head())

Brain Cancer Dataset
Shape: (88, 7)

   Unnamed: 0     sex   diagnosis             loc  ki    gtv  status
0           1  Female  Meningioma  Infratentorial  90   6.11       0
1           2    Male   HG glioma  Supratentorial  90  19.35       1
2           3  Female  Meningioma  Infratentorial  70   7.95       0
3           4  Female   LG glioma  Supratentorial  80   7.61       1
4           5    Male   HG glioma  Supratentorial  90   5.06       1

### Wage

In [8]:
wage_df = pd.read_csv(
    "dataset/DT-Wage.csv"
)

print("Wage Dataset")
print("Shape:", wage_df.shape)

display(wage_df.head())

Wage Dataset
Shape: (3000, 11)

,year,age,maritl,race,education,region,jobclass,health,health_ins,logwage,wage
0,2006,18,1. Never Married,1. White,1. < HS Grad,2. Middle Atlantic,1. Industrial,1. <=Good,2. No,4.318063,75.043154
1,2004,24,1. Never Married,1. White,4. College Grad,2. Middle Atlantic,2. Information,2. >=Very Good,2. No,4.255273,70.476020
2,2003,45,2. Married,1. White,3. Some College,2. Middle Atlantic,1. Industrial,1. <=Good,1. Yes,4.875061,130.982177
3,2003,43,2. Married,3. Asian,4. College Grad,2. Middle Atlantic,2. Information,2. >=Very Good,1. Yes,5.041393,154.685293
4,2005,50,4. Divorced,1. White,2. HS Grad,2. Middle Atlantic,2. Information,1. <=Good,1. Yes,4.318063,75.043154

### Credit

In [10]:
credit_df = pd.read_csv(
    "dataset/DT-Credit.csv"
)

print("Credit Dataset")
print("Shape:", credit_df.shape)

display(credit_df.head())

Credit Dataset
Shape: (400, 11)

,Income,Limit,Rating,Cards,Age,Education,Own,Student,Married,Region,Balance
0,14.891,3606,283,2,34,11,No,No,Yes,South,333
1,106.025,6645,483,3,82,15,Yes,Yes,Yes,West,903
2,104.593,7075,514,4,71,11,No,No,No,West,580
3,148.924,9504,681,3,36,11,Yes,No,No,West,964
4,55.882,4897,357,2,68,16,No,No,Yes,South,331

In [11]:
print("========== CAR EVALUATION ==========")
print(car_df.info())

print("\n========== BRAIN CANCER ==========")
print(brain_df.info())

print("\n========== WAGE ==========")
print(wage_df.info())

print("\n========== CREDIT ==========")
print(credit_df.info())

========== CAR EVALUATION ==========
<class 'pandas.DataFrame'>
RangeIndex: 1728 entries, 0 to 1727
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   buying    1728 non-null   str
 1   maint     1728 non-null   str
 2   doors     1728 non-null   str
 3   persons   1728 non-null   str
 4   lug_boot  1728 non-null   str
 5   safety    1728 non-null   str
 6   class     1728 non-null   str
dtypes: str(7)
memory usage: 133.5 KB
None

========== BRAIN CANCER ==========
<class 'pandas.DataFrame'>
RangeIndex: 88 entries, 0 to 87
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  88 non-null     int64
 1   sex         88 non-null     str
 2   diagnosis   87 non-null     str
 3   loc         88 non-null     str
 4   ki          88 non-null     int64
 5   gtv         88 non-null     float64
 6   status      88 non-null     int64
dtypes: float64(1), int64(3), str(3)
memory usage: 7.3 KB
None

========== WAGE ==========
<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   year        3000 non-null   int64
 1   age         3000 non-null   int64
 2   maritl      3000 non-null   str
 3   race        3000 non-null   str
 4   education   3000 non-null   str
 5   region      3000 non-null   str
 6   jobclass    3000 non-null   str
 7   health      3000 non-null   str
 8   health_ins  3000 non-null   str
 9   logwage     3000 non-null   float64
 10  wage        3000 non-null   float64
dtypes: float64(2), int64(2), str(7)
memory usage: 500.2 KB
None

========== CREDIT ==========
<class 'pandas.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 11 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Income     400 non-null    float64
 1   Limit      400 non-null    int64
 2   Rating     400 non-null    int64
 3   Cards      400 non-null    int64
 4   Age        400 non-null    int64
 5   Education  400 non-null    int64
 6   Own        400 non-null    str
 7   Student    400 non-null    str
 8   Married    400 non-null    str
 9   Region     400 non-null    str
 10  Balance    400 non-null    int64
dtypes: float64(1), int64(6), str(4)
memory usage: 39.1 KB
None

In [12]:
def split_dataset(df):
    

    train, temp = train_test_split(
        df,
        test_size=0.30,
        shuffle=False
    )
    

    validation, test = train_test_split(
        temp,
        test_size=0.50,
        shuffle=False
    )
    
    return train, validation, test

In [14]:
car_train, car_val, car_test = split_dataset(car_df)

brain_train, brain_val, brain_test = split_dataset(brain_df)

wage_train, wage_val, wage_test = split_dataset(wage_df)

credit_train, credit_val, credit_test = split_dataset(credit_df)

datasets = {
    "Car Evaluation": (
        car_train,
        car_val,
        car_test
    ),
    
    "Brain Cancer": (
        brain_train,
        brain_val,
        brain_test
    ),
    
    "Wage": (
        wage_train,
        wage_val,
        wage_test
    ),
    
    "Credit": (
        credit_train,
        credit_val,
        credit_test
    )
}

for name, (train, validation, test) in datasets.items():
    
    total = len(train) + len(validation) + len(test)
    
    print("\n", "=" * 50)
    print(name)
    print("=" * 50)
    
    print(
        "Training:",
        len(train),
        f"({len(train)/total*100:.2f}%)"
    )
    
    print(
        "Validation:",
        len(validation),
        f"({len(validation)/total*100:.2f}%)"
    )
    
    print(
        "Testing:",
        len(test),
        f"({len(test)/total*100:.2f}%)"
    )

 ==================================================
Car Evaluation
==================================================
Training: 1209 (69.97%)
Validation: 259 (14.99%)
Testing: 260 (15.05%)

 ==================================================
Brain Cancer
==================================================
Training: 61 (69.32%)
Validation: 13 (14.77%)
Testing: 14 (15.91%)

 ==================================================
Wage
==================================================
Training: 2100 (70.00%)
Validation: 450 (15.00%)
Testing: 450 (15.00%)

 ==================================================
Credit
==================================================
Training: 280 (70.00%)
Validation: 60 (15.00%)
Testing: 60 (15.00%)

In [ ]:
def classification_metrics(y_true, y_pred):
    
    y_true = np.array(y_true)
    y_pred = np.array(y_pred)
    
    classes = np.unique(
        np.concatenate((y_true, y_pred))
    )
    
    accuracy = np.mean(
        y_true == y_pred
    )
    
    precision_list = []
    recall_list = []
    f1_list = []
    
    for cls in classes:
        
        TP = np.sum(
            (y_true == cls) &
            (y_pred == cls)
        )
        
        FP = np.sum(
            (y_true != cls) &
            (y_pred == cls)
        )
        
        FN = np.sum(
            (y_true == cls) &
            (y_pred != cls)
        )
        
        if TP + FP == 0:
            precision = 0
        else:
            precision = TP / (TP + FP)
        
        if TP + FN == 0:
            recall = 0
        else:
            recall = TP / (TP + FN)
        
        if precision + recall == 0:
            f1 = 0
        else:
            f1 = (
                2 * precision * recall /
                (precision + recall)
            )
        
        precision_list.append(precision)
        recall_list.append(recall)
        f1_list.append(f1)
    
    return {
        "Accuracy": accuracy,
        "Precision": np.mean(precision_list),
        "Recall": np.mean(recall_list),
        "F1": np.mean(f1_list)
    }


def regression_metrics(y_true, y_pred):
    
    y_true = np.array(y_true)
    y_pred = np.array(y_pred)
    
    
    mae = np.mean(
        np.abs(y_true - y_pred)
    )
    
    
    mse = np.mean(
        (y_true - y_pred) ** 2
    )
    
    
    rmse = np.sqrt(mse)
    
    
    ss_res = np.sum(
        (y_true - y_pred) ** 2
    )
    
    ss_tot = np.sum(
        (y_true - np.mean(y_true)) ** 2
    )
    
    r2 = 1 - (ss_res / ss_tot)
    
    
    non_zero = y_true != 0
    
    mape = np.mean(
        np.abs(
            (y_true[non_zero] -
             y_pred[non_zero])
            /
            y_true[non_zero]
        )
    ) * 100
    
    return {
        "MAE": mae,
        "MSE": mse,
        "RMSE": rmse,
        "R2": r2,
        "MAPE": mape
    }